server:
  port: 8080
  shutdown: graceful
  
logging:
  level[com.weddingPlannerBackend]: DEBUG
  level[org.springframework.web]: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
redirectUrl: http://localhost:3000/auth
baseUrl: http://localhost:8080

spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wedding_planner
    username: root
    password: Password123#@!
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: rasmaa1999@gmail.com
    password: hefijiufgxschfga
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            

          
